USE [master]
GO

/****** Object:  Database [Haiku]    Script Date: 2/11/2018 7:42:53 PM ******/
CREATE DATABASE [Haiku]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Haiku', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Haiku.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Haiku_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Haiku_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Haiku] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Haiku].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Haiku] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Haiku] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Haiku] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Haiku] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Haiku] SET ARITHABORT OFF 
GO

ALTER DATABASE [Haiku] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Haiku] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Haiku] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Haiku] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Haiku] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Haiku] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Haiku] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Haiku] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Haiku] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Haiku] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Haiku] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Haiku] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Haiku] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Haiku] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Haiku] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Haiku] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Haiku] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Haiku] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Haiku] SET  MULTI_USER 
GO

ALTER DATABASE [Haiku] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Haiku] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Haiku] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Haiku] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Haiku] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Haiku] SET QUERY_STORE = OFF
GO

USE [Haiku]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Haiku] SET  READ_WRITE 
GO


